baseURL = "https://blog.lumysia.net/"
theme = "LoveIt"

copyright = "© 2025-2025 Livia Z."
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    weight = 1
    title = "Lumysia's Grimoire"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "home"
      pre = ""
      post = ""
      name = "Home"
      url = "/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
    [[languages.en.menu.main]]
      weight = 10
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""

  [languages.zh-cn]
    weight = 2
    title = "璐㛓娅的魔法书"
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "home"
      pre = ""
      post = ""
      name = "主页"
      url = "/zh-cn/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 10
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""

[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/Lumysia/blog"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "Lumysia's Grimoire"
  description = "Welcome to Lumysia's Grimoire. A digital spellbook where complex tech topics are decoded into powerful spells. Explore secrets of programming, reverse engineering, and software development."
  images = ["/logo_square.svg"]

  [params.author]
    name = "Lumysia"
    email = "sovranova@outlook.com"
    link = "https://github.com/Lumysia"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = ""
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2019
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "Lumysia's Grimoire"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.png"
      title = ""
      subtitle = "Welcome to Lumysia's Grimoire. A digital spellbook where complex tech topics are decoded into powerful spells."
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "Lumysia"
    Linkedin = ""
    X = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    ORCID = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki = ""
    Plume = ""
    HackTheBox = ""
    RootMe = ""
    Malt = ""
    TikTok = ""
    TryHackMe = ""
    Codeberg = ""
    HuggingFace = ""
    Threads = ""
    Phone = ""
    Email = "sovranova@outlook.com"
    RSS = true

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.share]
      enable = true
      X = true
      Twitter = false
      Threads = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = true
      Mix = false
      Telegram = true
    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta = ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        emoji = ""
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
      [params.page.comment.utterances]
        enable = false
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      [params.page.comment.giscus]
        enable = true
        repo = "Lumysia/blog"
        repoId = "R_kgDOP7sBAw"
        category = "Comments"
        categoryId = "DIC_kwDOP7sBA84CwNkN"
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = "Lumysia"
        logoUrl = "https://blog.lumysia.net/images/avatar.png"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  [params.seo]
    image = "/images/default-share-image.jpg"
    thumbnailUrl = "/images/default-share-image.jpg"

  [params.analytics]
    enable = true
    [params.analytics.google]
      id = ""
      anonymizeIP = true
      respectDoNotTrack = false
    [params.analytics.fathom]
      id = ""
      server = ""
    [params.analytics.plausible]
      dataDomain = ""
    [params.analytics.yandexMetrica]
      id = ""

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = "This website uses Cookies to improve your experience."
      dismiss = "Got it!"
      link = "What are cookies?"

  [params.cdn]
    data = ""
  [params.compatibility]
    polyfill = false
    objectFit = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":contentbasename"

[privacy]
  [privacy.googleAnalytics]
  [privacy.twitter]
  [privacy.youtube]

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[frontmatter]
  lastmod = [":git"]
